---
name: "metadata issue"
about: For issues that involve our metadata.
title: "metadata: meaningful title for the issue"
labels: metadata
assignees: pablorosado,lucasrodes

---

<!--
INSTRUCTIONS
Write a meaningful title that describes your issue/feedback for our metadata.

You may report:
- Bugs related to metadata.
- Confusing fields (unsure what they mean?).
- Suggestions for metadata changes or new use cases for the existing fields.
- Issues with how the metadata is propagated to Grapher and presented in a data page or the sources tab of a chart.

-->

### One-liner
<!-- Replace this line with a short description. (REQUIRED) -->

### Context & details
<!-- If possible, replace this line with more context and details. Otherwise, remove this section from the template. 

It helps if you provide screenshots
-->
